version: '3.3'
services:
  frontend:
    image: nginx:alpine
    ports:
        - 8000:80
    volumes:
        - ./frontend:/usr/share/nginx/html
  hcm-api:
    build:
      context: .
      dockerfile: ./Dockerfile.api
    container_name: hcm-api
    ports:
      - '3001:3001'
    depends_on:
      kafka:
        condition: service_healthy

  hcm-consumer:
    build:
      context: .
      dockerfile: ./Dockerfile.consumer
    container_name: hcm-consumer
    depends_on:
      kafka:
        condition: service_healthy
  
  zookeeper:
    image: confluentinc/cp-zookeeper:5.4.1
    container_name: zookeeper
    restart: unless-stopped
    ports:
        - "2181:2181"
    environment:
        ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
        test: "echo stat | nc localhost $$ZOOKEEPER_CLIENT_PORT"
        start_period: 1m

  kafka:
    image: confluentinc/cp-kafka:5.4.1
    container_name: kafka
    restart: unless-stopped
    depends_on:
        - filebeat
        - zookeeper
    ports:
        - "29092:29092"
    environment:
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_DELETE_TOPIC_ENABLE: "true"
    healthcheck:
        test: [ "CMD", "nc", "-z", "localhost", "9092" ]
        start_period: 1m
